name: Deploy to EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: SSH and deploy to EC2
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ubuntu
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      cd ~/cicd-test
                      git pull origin main
                      yarn install
                      yarn build
                      pm2 restart app || pm2 start yarn --name "app" -- start -p 3000 -H 0.0.0.0
